<a href="https://colab.research.google.com/github/nakajinbee/zero-tuku-deep-learning-2/blob/main/neural_network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

def sigmoid(x):
  return 1 /(1 + np.exp(-x))

x = np.random.randn(10, 2)
w1 = np.random.randn(2, 4)
b1 = np.random.randn(4)
w2 = np.random.randn(4, 3)
b2 = np.random.randn(3)

h = np.dot(x,w1) + b1
print("hの値：")
print(h)
a = sigmoid(h)
print("aの値：")
print(a)
s = np.dot(a, w2) + b2
print("sの値")
print(s)

hの値：
[[-2.07439765 -0.59662005 -1.29838164  1.02921246]
 [-0.06997036 -0.42510367 -1.48152235  1.30131949]
 [-0.84808991 -0.3674789  -1.52762067  1.30048861]
 [-1.86258916 -0.64083021 -1.2589198   1.00537094]
 [-3.45507327 -0.94524166 -0.95476799  0.64731298]
 [-2.77899259 -0.57771404 -1.30872928  1.00038504]
 [-1.20254129 -0.28111894 -1.60533567  1.35082893]
 [-2.6328811  -0.58959349 -1.29907401  0.99964755]
 [-3.05026141 -0.60378358 -1.28124792  0.96114852]
 [-1.60987084 -0.7073262  -1.19886551  0.96532551]]
aの値：
[[0.11161025 0.35511735 0.21443751 0.73676319]
 [0.48251454 0.39529613 0.18519759 0.78605697]
 [0.2998337  0.40915035 0.17834208 0.7859172 ]
 [0.13440155 0.34505889 0.2211599  0.73211326]
 [0.03061792 0.27984277 0.27792695 0.65640469]
 [0.05846999 0.35945876 0.21269956 0.73113427]
 [0.23102344 0.43017947 0.1672372  0.79426511]
 [0.067052   0.35672813 0.2143209  0.73098928]
 [0.04520619 0.35347855 0.21733788 0.7233517 ]
 [0.16660655 0.33018992 0.2316771  0.72418679]]
sの値
[[-1

In [2]:
# Sigmoidレイア 
class Sigmoid:
  def __init__(self):
    self.params = []
  
  def forward(self, x):
    return 1/(1 + np.exp(-x))

In [12]:
# 全結合層レイアであるAffineレイア
class Affine:
  def __init__(self, w, b):
    self.params = [w, b]
  
  def forward(self,x):
    w, b = self.params
    out = np.dot(x, w) + b
    return out
    

In [13]:
class TwoLayerNet:
  def __init__(self, input_size, hidden_size, output_size):
    I, H, O = input_size, hidden_size, output_size

    # 重みとバイアスの初期化
    self.layers = [
                   Affine(w1, b1),
                   Sigmoid(),
                   Affine(w2, b2)
    ]

    # 全ての重みをリストにまとめる
    self.params = []
    for layer in self.layers:
      self.params += layer.params
    
  def predict(self, x):
    for layer in self.layers:
      x = layer.forward(x)
    return x
  

In [15]:
x = np.random.randn(10, 2)
model = TwoLayerNet(2, 4, 3)
s = model.predict(x)

print(s)

[[-1.06955232 -1.35374389 -1.44557189]
 [-1.15637013 -1.96181552 -0.96842882]
 [-1.11067041 -1.55404196 -1.29733003]
 [-0.99770556 -1.08858873 -1.72045819]
 [-1.12561968 -1.6303288  -1.22505589]
 [-1.0918679  -1.45008665 -1.36582865]
 [-1.10517573 -1.51235295 -1.31840648]
 [-1.12137875 -1.64339535 -1.2219713 ]
 [-1.11710149 -1.60273916 -1.25667956]
 [-1.04511742 -1.2544899  -1.52438622]]
